Дано два файла:

- orders.csv, содержащий данные о заказах;
- products.csv, содержащий данные о товарах.

Прочитайте данные файлы, посмотрите на содержимое таблиц и проанализируйте его.

Подумайте, как связаны данные таблицы (какими ключевыми столбцами).

Объедините заданные таблицы в таблицу orders_products, чтобы в результирующей таблице оказалась информация обо всех заказах, но не оказалось информации о продуктах, на которых заказов ещё не поступало.

In [2]:
import pandas as pd

orders = pd.read_csv('./data/shop/orders.csv', sep=';')
orders.head(10)

,Дата создания,Order ID,ID Покупателя,Статус,Оплачен,Отменен,Отгружен,ID товара,Количество
0,09.11.2019 21:55:51,9,10,"Принят, ожидается оплата",Нет,Нет,Нет,103,5
1,09.11.2019 15:05:57,8,9,"Принят, ожидается оплата",Нет,Нет,Нет,86,100
2,09.11.2019 15:05:57,8,9,"Принят, ожидается оплата",Нет,Нет,Нет,104,10
3,09.11.2019 12:50:07,7,8,"Принят, ожидается оплата",Нет,Нет,Нет,104,7
4,09.11.2019 12:00:00,6,1,"Принят, ожидается оплата",Нет,Нет,Нет,104,5
5,09.11.2019 12:00:00,6,1,"Принят, ожидается оплата",Нет,Нет,Нет,103,5
6,08.11.2019 08:36:22,5,5,Отменён,Нет,Да,Нет,124,1
7,08.11.2019 08:36:22,4,9,"Принят, ожидается оплата",Нет,Нет,Да,91,1
8,08.11.2019 08:36:22,3,8,"Оплачен, формируется к отправке",Да,Нет,Нет,103,3
9,08.11.2019 08:36:22,3,8,"Оплачен, формируется к отправке",Да,Нет,Нет,104,3

In [3]:
products = pd.read_csv('./data/shop/products.csv', sep=';')
products.head(10)

   Product_ID                      Name  Price CURRENCY
0          47      Шатны Полосатый рейс   2999      RUR
1          51  Платье Аленький цветочек   4999      RUR
2          53    Штаны Цветочная Поляна   4999      RUR
3          71       Платье Ночная Жизнь   7999      RUR
4          74  Платье Ночная Жизнь XXXL   8999      RUR
5          86        Носки Простые, муж     45      RUR
6          91        Носки Честные, муж     50      RUR
7         103     Носки Подарочные, муж    199      RUR
8         104     Носки Подарочные, жен    249      RUR
9         124      Носки беговые Camino    999      RUR

In [8]:
orders_products = orders.merge(products, left_on='ID товара', right_on='Product_ID', how='left')
orders_products.head(10)

,Дата создания,Order ID,ID Покупателя,Статус,Оплачен,Отменен,Отгружен,ID товара,Количество,Product_ID,Name,Price,CURRENCY
0,09.11.2019 21:55:51,9,10,"Принят, ожидается оплата",Нет,Нет,Нет,103,5,103.0,"Носки Подарочные, муж",199.0,RUR
1,09.11.2019 15:05:57,8,9,"Принят, ожидается оплата",Нет,Нет,Нет,86,100,86.0,"Носки Простые, муж",45.0,RUR
2,09.11.2019 15:05:57,8,9,"Принят, ожидается оплата",Нет,Нет,Нет,104,10,104.0,"Носки Подарочные, жен",249.0,RUR
3,09.11.2019 12:50:07,7,8,"Принят, ожидается оплата",Нет,Нет,Нет,104,7,104.0,"Носки Подарочные, жен",249.0,RUR
4,09.11.2019 12:00:00,6,1,"Принят, ожидается оплата",Нет,Нет,Нет,104,5,104.0,"Носки Подарочные, жен",249.0,RUR
5,09.11.2019 12:00:00,6,1,"Принят, ожидается оплата",Нет,Нет,Нет,103,5,103.0,"Носки Подарочные, муж",199.0,RUR
6,08.11.2019 08:36:22,5,5,Отменён,Нет,Да,Нет,124,1,124.0,Носки беговые Camino,999.0,RUR
7,08.11.2019 08:36:22,4,9,"Принят, ожидается оплата",Нет,Нет,Да,91,1,91.0,"Носки Честные, муж",50.0,RUR
8,08.11.2019 08:36:22,3,8,"Оплачен, формируется к отправке",Да,Нет,Нет,103,3,103.0,"Носки Подарочные, муж",199.0,RUR
9,08.11.2019 08:36:22,3,8,"Оплачен, формируется к отправке",Да,Нет,Нет,104,3,104.0,"Носки Подарочные, жен",249.0,RUR

In [14]:
# 8.8
# Какой идентификатор (Order ID) имеет заказ, для которого не оказалось информации о товаре?
orders_products[orders_products['Name'].isna()]['Order ID'].values[0]

0

In [16]:
# 8.9
# На какой товар была произведена отмена?
# В качестве ответа запишите название этого товара (Name).
orders_products.query('Статус == "Отменён"')['Name'].values[0]

'Носки беговые Camino'

In [19]:
orders_products['Статус'].unique()

array(['Принят, ожидается оплата', 'Отменён',
       'Оплачен, формируется к отправке', 'Выполнен'], dtype=object)

In [23]:
# 8.10
# Какой покупатель принёс наибольшую суммарную прибыль интернет-магазину за указанный период?
# В ответ запишите идентификатор этого покупателя (ID Покупателя).
# Прибыль состоит только из оплаченных заказов и рассчитывается как количество купленного товара, умноженное на его цену.
orders_products['common price'] = orders_products['Price']*orders_products['Количество']
orders_products.query('Оплачен == "Да"')\
    .groupby('ID Покупателя')['common price'].sum().idxmax()

7